### ISSUE TITLE
Family sharing (de)authorize devices/accounts

### ISSUE THREAD

**Issue by Revadike** [DoctorMcKay/node-steam-user#267]
Continuation of https://github.com/DoctorMcKay/node-steam-user/issues/128
I'd like to see if it possible to authorize or deauthorize accounts/devices for family sharing. Could be useful as donating option for apps like SteamDB.
I could look into it myself, but please point me in the right direction.

**Comment by DoctorMcKay** [comment]
Okay, so I did some research on how family sharing works, and I think Valve's implementation is faulty. When you authorize a computer, you get back a "device token", which I believe is linked to a sentry file. When someone logs onto Steam on a computer with a library sharing authorization, it sends `ClientUseLocalDeviceAuthorization` with all of the tokens assigned to this machine, which apparently unlocks the appropriate shared libraries. Sending this with a token not assigned to the sentry file currently in use does not unlock the library.

*However*, if you don't send `ClientUseLocalDeviceAuthorization` at all, the license list sent to you includes all the games owned by people who shared their libraries with you, even if you aren't on an authorized machine. You can launch whatever shared games you want, *and [IPlayerService/IsPlayingSharedGame](https://steamapi.xpaw.me/#IPlayerService/IsPlayingSharedGame) doesn't show you as using a borrowed license*. Also, if the license owner launches a game, you don't get booted.

That said, if you call `ClientUseLocalDeviceAuthorization`, then the shared licenses get taken away and you're booted from any shared games you're playing. I wonder if there's a way by which the Steam client can be blocked from sending `ClientUseLocalDeviceAuthorization`, thus unlocking all shared games as if you owned them. Simply deleting the auth token from config.vdf doesn't seem to accomplish it, as the message still gets sent, but with no tokens. I bet a program could be developed to hook into the Steam client and block the message from being sent.

Anyway, here's what happens when you authorize a device (and a user):

First `ClientAuthorizeLocalDeviceRequest` is sent (as a job message)
- `device_description` - Computer name
- `owner_account_id` - The current account's ID
- `local_device_token` - 0

The response is a `CMsgClientAuthorizeLocalDevice` containing:
- `eresult` - 1
- `owner_account_id` - The current account's ID
- `authed_device_token` - The resulting device token

Then to add an authorized borrower account, you call `DeviceAuth.AddAuthorizedBorrowers#1` with:
- `steamid` - The current account's SteamID
- `steamid_borrower` - An array of SteamIDs to add to the auth list

The reply is fairly meaningless.

I'll see about adding support for this in the near future.
