### ISSUE TITLE
Promise on logOn

### ISSUE THREAD

**Issue by DAmNRelentless** [DoctorMcKay/node-steam-user#286]
**Is your feature request related to a problem? Please describe.**
You can run into problems when the login fails because the error event is fired then.

**Describe the solution you'd like**
It would be cool if the logOn event supports promises like so:
`
SteamUser.logOn({
  username,
  password
}).then(steamClient => {
  //you are now connected
}).catch(e => {
  //an error occured during connecting
})
`

**Describe alternatives you've considered**
You could also use the error event but that's also triggered in other cases and could cause false-positives.

**Comment by DoctorMcKay** [comment]
I have considered this and I've decided that I'm not going to implement this.

If it were implemented, the idea would be to route the `loggedOn` event to the Promise's resolve function, and the `error` event to the Promise's reject function. The problem is, if an error occurs, it's guaranteed to crash the application (at least in the future, when unhandled promise rejections turn into fatal errors) unless you handle both the Promise's rejection **and** the `error` event, since unhandled `error` events crash the application.
