### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by Alex-Nabu** [DoctorMcKay/node-steam-user#3]
I'm having a problem seeing increased memory usage in a lib i'm writing that depends on this lib. I suppose the problem may lay in my own code and is most likely but the heap dumps from the chrome profiler are not very helpful to me and look like a lot of system stuff which should be cleaned. Doc can you take a look at them and let me know whats using up the memory. what module function ect ? Dont want to publicly post the heaps oc for obvious reasons

**Comment by DoctorMcKay** [comment]
If you can privately get me any data you have, I'd need at least *something* to look at.

**Comment by Alex-Nabu** [comment]
ok much appreciated. send me a email so I can get your contact. king.zan@hotmail.com

**Comment by rodeyseijkens** [comment]
First I want to say thank you for this awesome library!

I also have some questions about the general memory usage of node-steam-user.
Once logged in for example is the typical memory usage +/- 200mb?

I'm currently working on this whole new client in NW.js (Node-Webkit) and it would be nice to know if I do something wrong or that this is the general memory usage of this library.

Once again thank you for your work.

![sneaky-peaky](https://cloud.githubusercontent.com/assets/846754/9833721/41ca10ba-59a2-11e5-9b68-6c48e9d322f4.jpg)

**Comment by DoctorMcKay** [comment]
If that 200 MB is what your entire app uses, then I'm sure most of it is just WebKit.

**Comment by rodeyseijkens** [comment]
Ok I think I have figured it out.

Starting app: +/-40MB
This is with loaded assets and javascript files (backbone, underscore, handlebars, jquery), this is without require(node-steam-user). After this nothing is changed model/view/html wise etc.

With require: +/-70MB
After login: +/- 90MB

When I start to fetch the entire friend list it starts to go up.I disabled the SteamFriends handlers etc because that contains the full personas too (I know that they are going to be removed). 

[Users](https://github.com/DoctorMcKay/node-steam-user#users) still contains all that persona info, which probably is taking up a lot of MBs. This depends of course on the amount of fetched friends, in my case +/- 160. So after that users fetch its +/- 110MB, so this comes to about 70MB (without the baseline), which is fine I guess, but maybe the [Users](https://github.com/DoctorMcKay/node-steam-user#users) could be empty but that is for you to decide.
