### ISSUE TITLE
'cellid' File?

### ISSUE THREAD

**Issue by StevePavlin** [DoctorMcKay/node-steam-user#39]
Whenever I enter a steam guard code to initially verify an account, this file is created:
https://gyazo.com/3a1ae145ccdc9d4a7fe0578c790e71d9

Can you explain what this file does?

**Comment by Lagg** [comment]
It's supposed to be the datacenter/cluster/LAN/whatever's overarching ID in Valve's network that your account is on if I recall correctly.

**Comment by DoctorMcKay** [comment]
My goal with node-steam-user is to provide as much parity with the official Steam Client as possible. There have been instances in the past where unofficial clients all broke due to a backend change that didn't affect the official client. For example, a few months ago, clients were barred from logging on if they didn't send a well-formed machine ID in their login request. That change was reverted within about a half hour due to incompatibilities with the official Linux client, but there's nothing saying that something similar couldn't happen again.

After you log on, the CM sends you a "cell ID". Steam divides the world into regions, called "cells". [There's a list here.](https://github.com/SteamDatabase/SteamTracking/blob/master/ClientExtracted/steam/cached/CellMap.vdf) The official client saves this ID, and sends it back in subsequent login requests.

To provide parity, node-steam-user does the same.
