### ISSUE TITLE
Event on('licenses') shows empty licenses

### ISSUE THREAD

**Issue by rodeyseijkens** [DoctorMcKay/node-steam-user#8]
So the on Licenses event doesn't really trigger when it actually has fetched the licenses.
I hacked around the problem by adding a setTimeout like the example below, but it of course isn't neat.

Result => Null
```javascript
steamUser.on('licenses', function(){
    console.log('Result', steamUser['licenses']);
});
```

Result => Array[] of Licenses
```javascript
steamUser.on('licenses', function(){
    setTimeout(function(){
        console.log('Result', steamUser['licenses']);
    }, 0); // setTimeout 0ms actually lasts 13ms 
});
```

**Comment by DoctorMcKay** [comment]
This is not a bug. As per the documentation, the `licenses` property will be updated **after** the event is emitted.

The first property of the event's callback function is the new array of licenses. The reason for this is because the event is emitted when your owned licenses changes, and having both the old and new lists available allows you to compare them.

What you should be doing is this:

```js
steamUser.on('licenses', function(licenses) {
    console.log('Result', licenses);
});
```

**Comment by rodeyseijkens** [comment]
Ah my bad, overlooked the callback with the licenses argument.
